apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-dev
  template:
    metadata:
      labels:
        app: application-dev
    spec:
      containers:
        - name: application-dev
          image: 392493780390.dkr.ecr.ap-southeast-1.amazonaws.com/nodejs-tutorialspoint-kulnaree:latest
          ports:
            - containerPort: 80
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ENV

