apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-config
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: application-dev
            namespace: application-dev
            env: Dev
          - name: application-prod
            namespace: application-prod
            env: Prod
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:breezekul/nodejs-tutorialspoint.git
        targetRevision: master
        path: argocd/manifests/{{env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
